# File: debug_processor.py

from transformers import AutoProcessor

MODEL_ID = "google/siglip-base-patch16-224"

print("--- Starting Diagnostic Test ---")

try:
    # 1. Load the processor
    processor = AutoProcessor.from_pretrained(MODEL_ID)
    print("Processor loaded successfully.")

    # 2. Call the processor with padding=True
    # This is the critical line we are testing.
    text_inputs = processor(text=["a sample"], padding=True, return_tensors="pt")
    print("Processor called with padding=True.")

    # 3. Print the keys of the resulting object
    print("\n--- RESULTS ---")
    print("Keys generated by the processor:")
    print(text_inputs.keys())
    print("-----------------")

    # 4. Check for the specific key
    if 'attention_mask' in text_inputs:
        print("\n✅ SUCCESS: 'attention_mask' was found.")
    else:
        print("\n❌ FAILURE: 'attention_mask' was NOT found.")

except Exception as e:
    print(f"\nAn unexpected error occurred: {e}")